[package]
name = "limo_msgs"
version = "0.0.0"
edition = "2021"

[dependencies]
rosidl_runtime_rs = "0.3"
serde = { version = "1", optional = true, features = ["derive"] }
std_msgs = "*"
builtin_interfaces = "*"

[features]
serde = ['dep:serde', 'rosidl_runtime_rs/serde', 'std_msgs/serde', 'builtin_interfaces/serde']
